{{- if .Values.featureWriter.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fraud-inference-demo.featureWriterName" . }}
  labels:
    {{- include "fraud-inference-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: feast-feature-writer
spec:
  replicas: {{ .Values.featureWriter.replicaCount }}
  selector:
    matchLabels:
      {{- include "fraud-inference-demo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: feast-feature-writer
  template:
    metadata:
      labels:
        {{- include "fraud-inference-demo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: feast-feature-writer
    spec:
      serviceAccountName: {{ include "fraud-inference-demo.serviceAccountName" . }}
      containers:
        - name: feature-writer
          image: "{{ .Values.featureWriter.image.repository }}:{{ .Values.featureWriter.image.tag }}"
          imagePullPolicy: {{ .Values.featureWriter.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.featureWriter.containerPort }}
          env:
            - name: FEAST_REPO_PATH
              value: /feast
            - name: FEAST_REDIS_CONNECTION_STRING
              value: {{ printf "%s:%v" (include "fraud-inference-demo.redisName" .) .Values.redis.service.port | quote }}
            - name: FEAST_OFFLINE_STORE_TYPE
              value: {{ .Values.feast.offlineStore.type | quote }}
            - name: FEAST_POSTGRES_HOST
              value: {{ include "fraud-inference-demo.postgresName" . | quote }}
            - name: FEAST_POSTGRES_PORT
              value: {{ .Values.postgres.service.port | quote }}
            - name: FEAST_POSTGRES_DATABASE
              value: {{ .Values.postgres.database | quote }}
            - name: FEAST_POSTGRES_SCHEMA
              value: {{ .Values.postgres.schema | quote }}
            - name: FEAST_POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: FEAST_POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
            - name: FEAST_POSTGRES_SSLMODE
              value: {{ .Values.postgres.sslmode | quote }}
          {{- with .Values.featureWriter.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fraud-inference-demo.featureWriterName" . }}
  labels:
    {{- include "fraud-inference-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: feast-feature-writer
spec:
  selector:
    {{- include "fraud-inference-demo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: feast-feature-writer
  ports:
    - name: http
      port: {{ .Values.featureWriter.service.port }}
      targetPort: http
{{- end }}
