quarkus.http.port=8080
fraud.transformer.target-model=MODEL_A
fraud.transformer.strict-feature-validation=true
fraud.feast.url=http://feast-feature-server:6566
fraud.predictor.url=http://fraud-model-a-predictor/v1/models/fraud-model-a:predict
fraud.model.MODEL_A.feature-service=fraud_model_a_feature_service
fraud.model.MODEL_B.feature-service=fraud_model_b_feature_service
